---
coverage:
  precision: 2
  round: down
  range: "40...90"

  status:
    project:
      default:
        target: 50%
        threshold: 5%
      layer1:
        flags: [layer1]
        target: 60%
        threshold: 5%
      layer2:
        flags: [layer2]
        target: 70%
        threshold: 5%
      sidechain:
        flags: [sidechain]
        target: 75%
        threshold: 5%
      miners:
        flags: [miners]
        target: 30%
        threshold: 10%
      app:
        flags: [app]
        target: 80%
        threshold: 5%
      common:
        flags: [common]
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 60%
        threshold: 5%

flags:
  layer1:
    paths:
      - layer1-core/
  layer2:
    paths:
      - layer2-services/
  sidechain:
    paths:
      - sidechain/
  miners:
    paths:
      - miners/
  app:
    paths:
      - layer3-app/
  common:
    paths:
      - common/

ignore:
  - build/**
  - depends/**
  - external/**
  - third_party/**
  - contrib/**
  - tests/**
  - explorer/**
  - docs/**
  - miners/**  # Option A: standalone mining binaries excluded from coverage
  - layer1-core/drachmad.cpp  # interactive daemon entrypoint exercised manually
  - layer1-core/drachma_cli.cpp  # CLI tool exercised manually in deployments
  - build-cov/_deps/googletest-src/**
  - googletest/**
  - googlemock/**
