.TH DRACHMA-CLI 1 "January 2026" "drachma 0.1.0" "DRACHMA Core"
.SH NAME
drachma-cli \- DRACHMA RPC client
.SH SYNOPSIS
.B drachma-cli
[\fIOPTIONS\fR] \fICOMMAND\fR [\fIPARAMS\fR]
.SH DESCRIPTION
.B drachma-cli
is a command-line JSON-RPC client for the DRACHMA daemon (drachmad). It allows you to 
interact with the blockchain, manage wallets, and query node status.
.PP
This manual page documents the
.B drachma-cli
command. For information on specific RPC commands, use:
.B drachma-cli help
.SH OPTIONS
.TP
.BR \-rpcuser=\fIUSER\fR
Username for JSON-RPC connections
.TP
.BR \-rpcpassword=\fIPASSWORD\fR
Password for JSON-RPC connections
.TP
.BR \-rpcconnect=\fIIP\fR
Send commands to node running on IP (default: 127.0.0.1)
.TP
.BR \-rpcport=\fIPORT\fR
Connect to JSON-RPC on PORT (default: 8332 or testnet: 18332)
.TP
.BR \-rpcwait
Wait for RPC server to start
.TP
.BR \-version
Print version and exit
.TP
.BR \-help
Print help message and exit
.SH COMMANDS
The following are common RPC commands. For a complete list, run:
.B drachma-cli help
.TP
.BR getblockchaininfo
Returns an object containing various state info regarding blockchain processing
.TP
.BR getbalance " [" \fIACCOUNT\fR " [" \fIMINCONF\fR "]]"
Get the balance in the wallet
.TP
.BR getnewaddress " [" \fIACCOUNT\fR "]"
Generate a new address for receiving payments
.TP
.BR sendtoaddress " " \fIADDRESS\fR " " \fIAMOUNT\fR
Send an amount to a given address
.TP
.BR getpeerinfo
Get data about each connected network node
.TP
.BR getmininginfo
Get mining-related information
.TP
.BR stop
Stop the DRACHMA daemon
.SH EXAMPLES
.TP
Get blockchain information:
.B drachma-cli \-rpcuser=user \-rpcpassword=pass getblockchaininfo
.TP
Get wallet balance:
.B drachma-cli \-rpcuser=user \-rpcpassword=pass getbalance
.TP
Send 1.0 DRM to an address:
.B drachma-cli \-rpcuser=user \-rpcpassword=pass sendtoaddress "DRM1..." 1.0
.TP
Get help on a specific command:
.B drachma-cli help sendtoaddress
.SH FILES
.TP
.I ~/.drachma/drachma.conf
Configuration file (credentials can be specified here)
.SH SEE ALSO
.BR drachmad (1),
.BR drachma-qt (1)
.PP
Full documentation at: <https://github.com/Tsoympet/BlockChainDrachma>
.SH COPYRIGHT
Copyright \(co 2026 DRACHMA Blockchain contributors.
.PP
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
